# Air configuration for golang-web-mvc-project-template

root = "."
tmp_dir = "tmp"

[build]
# Main entrypoint
cmd = "go build -o ./tmp/app.exe ./app"
bin = "tmp/app.exe"
full_bin = "./tmp/app.exe"

# Watch for changes in these directories
include_dir = ["app", "views"]

# Ignore generated / dependency dirs
exclude_dir = ["tmp", "build", "dist", "tests", "vendor", ".git"]

include_ext = ["go", "tpl", "tmpl", "html"]
exclude_ext = ["swp", "tmp"]

delay = 1000 # ms

[log]
time = true

[color]
main = "yellow"
watcher = "cyan"
build = "green"
runner = "magenta"

[misc]
clean_on_exit = true

